---
# tasks file for bmw_suse_compute
 - include_tasks: prechecks.yml
 - include_tasks: system_facts.yml
 - include_tasks: set_silence.yml
 - include_tasks: openstack.yml
 - include_tasks: postchecks.yml
